linters-settings:
  wrapcheck:
    ignorePackageGlobs:
      - github.com/Vilsol/go-pob/*
      - golang.org/x/sync/errgroup*

linters:
  disable-all: true
  enable:
#    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
#    - unused
#    - varcheck
    - bidichk
    - contextcheck
    - durationcheck
    - errorlint
#    - goconst
    - goimports
    - revive
    - ifshort
    - misspell
    - prealloc
    - whitespace
    - wrapcheck

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA9003:"
    - linters:
        - whitespace
      text: "unnecessary leading newline"