name: push

permissions: read-all

on: [push, pull_request]

env:
  GO_VERSION: "1.19.0"
  NODE_VERSION: "18"

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout 5m

  test-x86:
    name: Test (x86)
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

  test-wasm:
    name: Test (wasm)
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: ./.github/wasm_test.sh
        env:
          GOOS: js
          GOARCH: wasm
